import { beforeEach, expect, it, vi } from 'vitest'
vi.unmock('@prisma/client')
import { Prisma } from '@prisma/client'
const m = vi.hoisted(() => ({ user: vi.fn(), attempts: vi.fn(), attempt: vi.fn(), tour: vi.fn(), existing: vi.fn(), create: vi.fn(), list: vi.fn(), count: vi.fn(), stats: vi.fn() }))
vi.mock('@/lib/server/auth', () => ({ getCurrentUser: m.user }))
vi.mock('@/lib/server/db', () => ({ db: { reviewAttempt: { count: m.attempts, create: m.attempt }, tour: { findUnique: m.tour }, review: { findUnique: m.existing, create: m.create, findMany: m.list, count: m.count, aggregate: m.stats } } }))
import { GET, POST } from '@/app/api/reviews/route'
import { WEBSITE_REVIEW_SCOPE } from '@/lib/review-scope'
const valid = { scope: 'website', rating: 4, title: 'Good trip', text: 'An enjoyable experience in Egypt.' }
const post = (body: unknown) => POST(new Request('http://localhost:3000/api/reviews', { method: 'POST', headers: { origin: 'http://localhost:3000' }, body: JSON.stringify(body) }))
beforeEach(() => { vi.clearAllMocks(); m.user.mockResolvedValue({ id: 'customer' }); m.attempts.mockResolvedValue(0); m.attempt.mockResolvedValue({}); m.tour.mockResolvedValue({ slug: 'real-tour' }); m.existing.mockResolvedValue(null); m.create.mockResolvedValue({ publicId: 'review', status: 'PENDING' }); m.list.mockResolvedValue([]); m.count.mockResolvedValue(0); m.stats.mockResolvedValue({ _avg: { rating: null }, _count: { rating: 0 } }) })
it('requires authentication and rejects cross-origin submissions', async () => { m.user.mockResolvedValue(null); expect((await post(valid)).status).toBe(401); expect((await POST(new Request('http://localhost:3000/api/reviews', { method: 'POST', headers: { origin: 'https://evil.example' }, body: '{}' }))).status).toBe(403); expect(m.create).not.toHaveBeenCalled() })
it.each([null, [], {}, { ...valid, rating: 0 }, { ...valid, rating: 2.5 }, { ...valid, text: 'short' }])('rejects invalid payload %j', async value => { expect((await post(value)).status).toBe(400); expect(m.create).not.toHaveBeenCalled() })
it('persists authenticated website reviews pending moderation with no invented tour', async () => { expect((await post(valid)).status).toBe(201); expect(m.tour).not.toHaveBeenCalled(); expect(m.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ tourSlug: WEBSITE_REVIEW_SCOPE, userId: 'customer', status: 'PENDING', rating: 4 }) })) })
it('preserves tour review lookup and scope', async () => { expect((await post({ tourSlug: 'real-tour', rating: 5, text: valid.text })).status).toBe(201); expect(m.tour).toHaveBeenCalledWith({ where: { slug: 'real-tour' }, select: { slug: true } }); expect(m.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ tourSlug: 'real-tour' }) })) })
it('rejects duplicates including concurrent uniqueness conflicts', async () => { m.existing.mockResolvedValueOnce({ id: 'existing' }); expect((await post(valid)).status).toBe(409); m.create.mockRejectedValueOnce(new Prisma.PrismaClientKnownRequestError('duplicate', { code: 'P2002', clientVersion: 'test' })); expect((await post(valid)).status).toBe(409) })
it('enforces attempt limits and handles failed persistence honestly', async () => { m.attempts.mockResolvedValueOnce(5); expect((await post(valid)).status).toBe(429); m.create.mockRejectedValueOnce(Error('private database details')); const response = await post(valid); expect(response.status).toBe(500); expect(JSON.stringify(await response.json())).not.toContain('private') })
it('lists only published website reviews with separate statistics and safe pagination', async () => { const response = await GET(new Request('http://localhost:3000/api/reviews?scope=website&page=no&limit=no')); expect(response.status).toBe(200); expect(m.list).toHaveBeenCalledWith(expect.objectContaining({ where: { tourSlug: WEBSITE_REVIEW_SCOPE, status: 'PUBLISHED' }, skip: 0, take: 10 })); expect((await response.json()).summary).toEqual({ average: null, count: 0 }); expect(m.tour).not.toHaveBeenCalled() })
it('does not expose website reviews through a forged tour slug', async () => { expect((await GET(new Request('http://localhost:3000/api/reviews?tourSlug=%40website'))).status).toBe(404) })
