-- CreateTable
CREATE TABLE `events` (
    `id` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(80) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `titleAr` VARCHAR(200) NULL,
    `image` VARCHAR(2000) NOT NULL,
    `date` VARCHAR(120) NOT NULL,
    `startDate` VARCHAR(10) NULL,
    `endDate` VARCHAR(10) NULL,
    `startTime` VARCHAR(5) NULL,
    `endTime` VARCHAR(5) NULL,
    `timezone` VARCHAR(60) NULL,
    `location` VARCHAR(120) NOT NULL,
    `locationAr` VARCHAR(120) NULL,
    `venueName` VARCHAR(200) NULL,
    `venueNameAr` VARCHAR(200) NULL,
    `address` VARCHAR(500) NULL,
    `addressAr` VARCHAR(500) NULL,
    `city` VARCHAR(120) NULL,
    `cityAr` VARCHAR(120) NULL,
    `mapQuery` VARCHAR(200) NULL,
    `copy` VARCHAR(2000) NOT NULL,
    `copyAr` VARCHAR(2000) NULL,
    `category` VARCHAR(120) NULL,
    `categoryAr` VARCHAR(120) NULL,
    `featured` BOOLEAN NOT NULL DEFAULT false,
    `intro` VARCHAR(2000) NULL,
    `introAr` VARCHAR(2000) NULL,
    `pricingType` VARCHAR(20) NULL,
    `price` DOUBLE NULL,
    `currency` VARCHAR(8) NULL,
    `capacity` INTEGER NULL,
    `bookingDeadline` VARCHAR(10) NULL,
    `organizerName` VARCHAR(200) NULL,
    `organizerPhone` VARCHAR(60) NULL,
    `organizerWhatsapp` VARCHAR(60) NULL,
    `organizerEmail` VARCHAR(200) NULL,
    `isPublished` BOOLEAN NOT NULL DEFAULT true,
    `displayOrder` INTEGER NOT NULL DEFAULT 999,
    `content` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `events_slug_key`(`slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cars` (
    `id` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(80) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `image` VARCHAR(2000) NOT NULL,
    `seats` VARCHAR(60) NOT NULL,
    `transmission` VARCHAR(60) NOT NULL,
    `dailyPrice` DOUBLE NOT NULL,
    `copy` VARCHAR(2000) NOT NULL,
    `credit` JSON NULL,
    `isPublished` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `cars_slug_key`(`slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
