'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { Anchor, ArrowRight, Clock3, Compass, HeartHandshake, Pause, Play, Route, Ship, Sun } from 'lucide-react'
import { destinations, siteImages } from '@/data/content'
import { tx, useLocale } from '@/components/locale'
import { isLocaleRTL, pickLocaleText } from '@/lib/locale-config'
import { HelpCTA, PageShowcaseHero, SiteShell } from '@/components/site'

const destinationNames: Record<string, string> = {
  'cairo-giza': 'القاهرة والجيزة', luxor: 'الأقصر', aswan: 'أسوان',
  hurghada: 'الغردقة', 'white-desert': 'الصحراء البيضاء',
}

const featuredDestinations = destinations.filter((item) => destinationNames[item.slug])

function AboutContent() {
  const { locale } = useLocale()
  const [paused, setPaused] = useState(false)
  const values = [
    { icon: Compass, title: tx(locale, { en: 'Your kind of Egypt', es: 'Egipto a tu manera', it: 'Il tuo Egitto', ar: 'وجهتك بطريقتك' }), copy: tx(locale, { en: 'Start with what you want to see, then leave room for the journey to breathe.', es: 'Empieza por lo que quieres ver y deja espacio para que el viaje respire.', it: 'Parti da ciò che vuoi vedere e lascia spazio al viaggio.', ar: 'نبدأ بما تحب رؤيته، ثم نترك للرحلة مساحة تتنفس فيها.' }) },
    { icon: Clock3, title: tx(locale, { en: 'Time to be there', es: 'Tiempo para estar allí', it: 'Tempo per viverlo', ar: 'وقت للتجربة' }), copy: tx(locale, { en: 'Meaningful places deserve time to understand, not just a quick stop.', es: 'Los lugares especiales merecen tiempo para comprenderlos, no solo una parada rápida.', it: 'I luoghi speciali meritano tempo per essere capiti, non solo una sosta veloce.', ar: 'الأماكن المهمة تستحق وقتًا لفهمها، لا مجرد المرور عليها.' }) },
    { icon: HeartHandshake, title: tx(locale, { en: 'Clarity in the details', es: 'Claridad en los detalles', it: 'Chiarezza nei dettagli', ar: 'تفاصيل واضحة' }), copy: tx(locale, { en: 'The route, services, and timing should be clear before you commit.', es: 'La ruta, los servicios y los horarios deben estar claros antes de reservar.', it: 'Itinerario, servizi e orari devono essere chiari prima di prenotare.', ar: 'المسار والخدمات والتوقيت أمور تُراجع قبل أن تلتزم بالرحلة.' }) },
  ]
  const ways = [
    { icon: Sun, title: tx(locale, { en: 'One-day tours', es: 'Circuitos de un día', it: 'Tour di un giorno', ar: 'رحلات اليوم الواحد' }), copy: tx(locale, { en: 'A focused day in Cairo, Luxor, or the place calling you most.', es: 'Un día completo en El Cairo, Luxor o el lugar que más te llame.', it: 'Una giornata intensa al Cairo, a Luxor o nel luogo che ti attira di più.', ar: 'يوم مركز في القاهرة أو الأقصر أو وجهتك المفضلة.' }), href: '/egypt-tours/one-day-tours', image: siteImages.cairo },
    { icon: Route, title: tx(locale, { en: 'Multi-day journeys', es: 'Viajes de varios días', it: 'Viaggi di più giorni', ar: 'رحلات متعددة الأيام' }), copy: tx(locale, { en: 'More time to connect the places and stories across Egypt.', es: 'Más tiempo para unir lugares e historias de todo Egipto.', it: 'Più tempo per collegare luoghi e storie di tutto l’Egitto.', ar: 'مساحة أكبر للتنقل بين حكايات مصر ومدنها.' }), href: '/egypt-tours/multi-days-tours', image: siteImages.pyramids },
    { icon: Ship, title: tx(locale, { en: 'Nile cruises', es: 'Cruceros por el Nilo', it: 'Crociere sul Nilo', ar: 'الرحلات النيلية' }), copy: tx(locale, { en: 'Follow the river through the temples and landscapes of the south.', es: 'Sigue el río entre los templos y paisajes del sur.', it: 'Segui il fiume tra templi e paesaggi del sud.', ar: 'رحلة بين ضفتي النيل ومعابد الجنوب.' }), href: '/egypt-tours/nile-cruises', image: siteImages.nile },
    { icon: Anchor, title: tx(locale, { en: 'Shore excursions', es: 'Excursiones en tierra', it: 'Escursioni a terra', ar: 'رحلات الموانئ' }), copy: tx(locale, { en: 'Make a ship call count with a route shaped around port time.', es: 'Aprovecha la escala del barco con una ruta adaptada al horario del puerto.', it: 'Sfrutta lo scalo della nave con un itinerario pensato per i tempi del porto.', ar: 'استغل وقت توقف السفينة في رحلة تناسب موعدها.' }), href: '/egypt-tours/shore-excursions', image: siteImages.redSea },
  ]
  const steps = [
    { number: '01', title: tx(locale, { en: 'Tell us your plans', es: 'Cuéntanos tus planes', it: 'Raccontaci i tuoi piani', ar: 'احكِ لنا عن رحلتك' }), copy: tx(locale, { en: 'Share your dates, travel party, and the places you hope to see.', es: 'Comparte tus fechas, tu grupo de viaje y los lugares que quieres ver.', it: 'Condividi date, gruppo di viaggio e luoghi che vuoi vedere.', ar: 'المواعيد، عدد المسافرين، والأماكن التي تتمنى زيارتها.' }) },
    { number: '02', title: tx(locale, { en: 'Find your rhythm', es: 'Encuentra tu ritmo', it: 'Trova il tuo ritmo', ar: 'اختَر الإيقاع المناسب' }), copy: tx(locale, { en: 'Compare a listed journey with a tailored request and choose what matters.', es: 'Compara un viaje del catálogo con una propuesta a medida y elige lo que importa.', it: 'Confronta un viaggio a catalogo con una proposta su misura e scegli ciò che conta.', ar: 'قارن بين رحلة جاهزة وطلب مخصص، وحدد ما يهمك فعلًا.' }) },
    { number: '03', title: tx(locale, { en: 'Confirm the details', es: 'Confirma los detalles', it: 'Conferma i dettagli', ar: 'راجع التفاصيل' }), copy: tx(locale, { en: 'Review the itinerary, price, inclusions, and timing with the team before booking.', es: 'Revisa el itinerario, el precio, las inclusiones y los horarios con el equipo antes de reservar.', it: 'Verifica itinerario, prezzo, inclusioni e orari con il team prima di prenotare.', ar: 'تأكد من البرنامج والسعر والمشمولات والتوقيت مع الفريق قبل الحجز.' }) },
  ]

  const destinationCards = (duplicate: boolean) => featuredDestinations.map((item) => (
    <li key={`${duplicate ? 'copy' : 'original'}-${item.slug}`}>
      <Link href={`/destinations/${item.slug}`} tabIndex={duplicate ? -1 : undefined} className="about-destination-card" dir={isLocaleRTL(locale) ? 'rtl' : 'ltr'}>
        <Image src={item.detail.heroImage} alt={item.detail.heroAlt} fill sizes="(max-width: 760px) 230px, 310px" />
        <span>{pickLocaleText(locale, { en: item.title, ar: destinationNames[item.slug] })}<ArrowRight size={19} aria-hidden="true" /></span>
      </Link>
    </li>
  ))

  return <main className="about-page">
    <PageShowcaseHero image={destinations[1].detail.heroImage} eyebrow={tx(locale, { en: 'Discover Egypt with us', es: 'Descubre Egipto con nosotros', it: 'Scopri l’Egitto con noi', ar: 'اكتشف مصر معنا' })} title="STAR PYRAMIDS" intro={tx(locale, { en: 'Journeys shaped around your curiosity, with room to experience Egypt at your own pace.', es: 'Viajes a medida de tu curiosidad, con espacio para vivir Egipto a tu manera.', it: 'Viaggi plasmati sulla tua curiosità, con spazio per vivere l’Egitto al tuo ritmo.', ar: 'رحلات تنطلق من شغفك بالمكان، وتترك لك وقتًا لتعيش مصر بطريقتك.' })} primaryLabel={tx(locale, { en: 'Discover our story', es: 'Descubre nuestra historia', it: 'Scopri la nostra storia', ar: 'اعرف قصتنا' })} primaryHref="#our-story" secondaryLabel={tx(locale, { en: 'See ways to travel', es: 'Ver formas de viajar', it: 'Vedi i modi di viaggiare', ar: 'شاهد طرق السفر' })} secondaryHref="#travel-styles" railLabel={tx(locale, { en: 'Who we are', es: 'Quiénes somos', it: 'Chi siamo', ar: 'من نحن' })} railTitle={tx(locale, { en: 'Egypt is more than a checklist.', es: 'Egipto es más que una lista de lugares.', it: 'L’Egitto è più di una lista di luoghi.', ar: 'مصر أكبر من قائمة أماكن.' })} railHref="#our-story" railMeta={[{ Icon: Compass, label: tx(locale, { en: 'Egypt-led journeys', es: 'Viajes guiados por Egipto', it: 'Viaggi guidati in Egitto', ar: 'رحلات داخل مصر' }) }, { Icon: Clock3, label: tx(locale, { en: 'At your own pace', es: 'A tu ritmo', it: 'Al tuo ritmo', ar: 'بإيقاع يناسبك' }) }]} statsLabel={tx(locale, { en: 'Experience summary', es: 'Resumen de la experiencia', it: 'Riepilogo dell’esperienza', ar: 'ملخص التجربة' })} stats={[{ value: featuredDestinations.length, label: tx(locale, { en: 'Featured places', es: 'Lugares destacados', it: 'Luoghi in evidenza', ar: 'وجهات مختارة' }) }, { value: ways.length, label: tx(locale, { en: 'Ways to travel', es: 'Formas de viajar', it: 'Modi di viaggiare', ar: 'طرق للسفر' }) }]}/>

    <section id="our-story" className="about-story about-section container" aria-labelledby="about-story-title">
      <div className="about-story-copy"><span className="eyebrow">{tx(locale, { en: 'Who we are', es: 'Quiénes somos', it: 'Chi siamo', ar: 'من نحن' })}</span><h2 id="about-story-title">{tx(locale, { en: 'Egypt is more than a checklist.', es: 'Egipto es más que una lista de lugares.', it: 'L\u2019Egitto è più di una lista di luoghi.', ar: 'مصر أكبر من قائمة أماكن.' })}</h2><p>{tx(locale, { en: 'At STAR PYRAMIDS, a good journey makes room for the landmarks you have dreamed of and the smaller moments that bring a place closer. That is why we offer different ways to explore Egypt, from a single day to a journey across its cities.', es: 'En STAR PYRAMIDS, un buen viaje deja espacio para los monumentos con los que soñaste y para los pequeños momentos que te acercan al lugar. Por eso ofrecemos distintas formas de explorar Egipto, desde un solo día hasta un viaje entre sus ciudades.', it: 'In STAR PYRAMIDS, un buon viaggio lascia spazio ai monumenti che hai sognato e ai piccoli momenti che ti avvicinano al luogo. Per questo offriamo diversi modi per esplorare l’Egitto, da un solo giorno a un viaggio tra le sue città.', ar: 'في STAR PYRAMIDS نرى أن الرحلة الجيدة تجمع بين المعالم التي حلمت بها والتفاصيل الصغيرة التي تجعل المكان أقرب إليك. لهذا نعرض طرقًا مختلفة لاستكشاف مصر، من يوم واحد إلى رحلة تمتد بين مدنها.' })}</p><p>{tx(locale, { en: 'Browse the journeys and destinations, or tell us what you have in mind to start a conversation about a route that fits your time and interests.', es: 'Explora los viajes y destinos, o cuéntanos tu idea para empezar a diseñar una ruta a medida de tu tiempo e intereses.', it: 'Sfoglia viaggi e destinazioni, oppure raccontaci la tua idea per iniziare a disegnare un itinerario su misura per tempi e interessi.', ar: 'تصفح الرحلات والوجهات، أو أخبرنا بما تفكر فيه لنبدأ حوارًا حول برنامج يناسب وقتك واهتماماتك.' })}</p><Link className="text-link" href="/contact">{tx(locale, { en: 'Talk to us', es: 'Habla con nosotros', it: 'Parla con noi', ar: 'تواصل معنا' })} <ArrowRight size={17}/></Link></div>
      <figure className="about-story-image"><Image src={siteImages.pyramids} alt={locale === 'ar' ? 'أبو الهول وأهرامات الجيزة' : 'The Sphinx and Pyramids of Giza'} fill sizes="(max-width: 900px) 100vw, 45vw" /><figcaption>{locale === 'ar' ? 'الجيزة، مصر' : 'Giza, Egypt'}</figcaption></figure>
    </section>

    <section className="about-values about-section" aria-labelledby="about-values-title"><div className="container"><div className="about-section-heading"><span className="eyebrow">{tx(locale, { en: 'Our approach', es: 'Nuestro enfoque', it: 'Il nostro approccio', ar: 'طريقتنا' })}</span><h2 id="about-values-title">{tx(locale, { en: 'The details make the difference.', es: 'Los detalles marcan la diferencia.', it: 'I dettagli fanno la differenza.', ar: 'التفاصيل تصنع الفرق.' })}</h2></div><div className="about-values-grid">{values.map(({icon:Icon,title,copy},index)=><article key={title}><span className="about-value-number">0{index+1}</span><Icon size={27} strokeWidth={1.7} aria-hidden="true"/><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="about-destinations about-section" aria-labelledby="about-destinations-title"><div className="container about-section-heading about-heading-row"><div><span className="eyebrow">{tx(locale, { en: 'Across Egypt', es: 'Por todo Egipto', it: 'In tutto l\u2019Egitto', ar: 'من مصر وإليها' })}</span><h2 id="about-destinations-title">{tx(locale, { en: 'Every place has a different story.', es: 'Cada lugar tiene una historia distinta.', it: 'Ogni luogo ha una storia diversa.', ar: 'لكل مكان حكاية مختلفة.' })}</h2><p>{tx(locale, { en: 'Follow the place that catches your eye and start your journey there.', es: 'Sigue el lugar que te llame la atención y empieza tu viaje allí.', it: 'Segui il luogo che ti colpisce e inizia il tuo viaggio da lì.', ar: 'اختَر المكان الذي يلفت انتباهك، ودع الرحلة تبدأ من هناك.' })}</p></div><button type="button" className="about-motion-toggle" aria-label={paused ? tx(locale, { en: 'Play destination slider', es: 'Reproducir el carrusel de destinos', it: 'Avvia il carosello delle destinazioni', ar: 'تشغيل حركة الوجهات' }) : tx(locale, { en: 'Pause destination slider', es: 'Pausar el carrusel de destinos', it: 'Metti in pausa il carosello delle destinazioni', ar: 'إيقاف حركة الوجهات' })} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused ? <Play size={18} fill="currentColor"/> : <Pause size={18} fill="currentColor"/>}</button></div><div className="about-marquee-viewport" aria-label={tx(locale, { en: 'Egypt destinations', es: 'Destinos de Egipto', it: 'Destinazioni in Egitto', ar: 'وجهات مصر' })}><div className={`about-marquee-track${paused ? ' is-paused' : ''}`}><ul className="about-marquee-list">{destinationCards(false)}</ul><ul className="about-marquee-list" aria-hidden="true">{destinationCards(true)}</ul></div></div></section>

    <section id="travel-styles" className="about-ways about-section container" aria-labelledby="about-ways-title"><div className="about-section-heading about-ways-heading"><div><span className="eyebrow">{tx(locale, { en: 'Ways to travel', es: 'Formas de viajar', it: 'Modi di viaggiare', ar: 'طرق السفر' })}</span><h2 id="about-ways-title">{tx(locale, { en: 'A journey for the time you have.', es: 'Un viaje a medida del tiempo que tienes.', it: 'Un viaggio su misura per il tempo che hai.', ar: 'رحلة تناسب الوقت الذي لديك.' })}</h2></div><p>{tx(locale, { en: 'From a few hours in one city to days along the Nile, start with the format that feels right.', es: 'Desde unas horas en una ciudad hasta días en el Nilo: empieza por el formato que prefieras.', it: 'Da poche ore in una città a giorni sul Nilo: inizia dal formato che preferisci.', ar: 'من ساعات في مدينة واحدة إلى أيام على النيل، ابدأ بالشكل الأقرب لك.' })}</p></div><div className="about-ways-grid">{ways.map(({icon:Icon,title,copy,href,image},index)=><Link key={href} href={href} className="about-way-card" aria-label={title}><Image src={image} alt="" fill sizes="(max-width: 760px) 100vw, 55vw"/><span className="about-way-shade"/><span className="about-way-top"><span>0{index+1}</span><Icon size={25} strokeWidth={1.7} aria-hidden="true"/></span><span className="about-way-card-copy"><strong>{title}</strong><small>{copy}</small></span><span className="about-way-action" aria-hidden="true"><ArrowRight size={20}/></span></Link>)}</div></section>

    <section className="about-process about-section" aria-labelledby="about-process-title"><div className="container about-process-layout"><div className="about-process-intro"><span className="eyebrow">{tx(locale, { en: 'From idea to itinerary', es: 'De la idea al itinerario', it: 'Dall\u2019idea all\u2019itinerario', ar: 'من الفكرة إلى الرحلة' })}</span><h2 id="about-process-title">{tx(locale, { en: 'Begin with a question. Go with a clear plan.', es: 'Empieza con una pregunta. Viaja con un plan claro.', it: 'Inizia con una domanda. Parti con un piano chiaro.', ar: 'ابدأ بسؤال. وانطلق بخطة واضحة.' })}</h2><p>{tx(locale, { en: 'You do not need every answer at the start. Begin with what you know, then review your options before making a decision.', es: 'No necesitas tener todas las respuestas al principio. Empieza por lo que sabes y revisa tus opciones antes de decidir.', it: 'Non serve avere tutte le risposte all’inizio. Parti da ciò che sai e valuta le opzioni prima di decidere.', ar: 'لا تحتاج إلى معرفة كل التفاصيل من البداية. ابدأ بما تعرفه، ثم راجع خياراتك قبل اتخاذ القرار.' })}</p><Link href="/make-your-trip" className="primary-btn">{tx(locale, { en: 'Start planning', es: 'Empieza a planificar', it: 'Inizia a pianificare', ar: 'ابدأ التخطيط' })} <ArrowRight size={17}/></Link></div><ol className="about-process-steps">{steps.map(step=><li key={step.number}><span>{step.number}</span><div><h3>{step.title}</h3><p>{step.copy}</p></div></li>)}</ol></div></section>

    <section className="about-closing" aria-labelledby="about-closing-title"><Image src={destinations[2].detail.heroImage} alt="" fill sizes="100vw"/><div className="about-closing-shade"/><div className="container about-closing-content"><span className="about-kicker">{tx(locale, { en: 'The next chapter', es: 'El próximo capítulo', it: 'Il prossimo capitolo', ar: 'الرحلة التالية' })}</span><h2 id="about-closing-title">{tx(locale, { en: 'Your Egypt is waiting.', es: 'Tu Egipto te espera.', it: 'Il tuo Egitto ti aspetta.', ar: 'مصر في انتظارك.' })}</h2><p>{tx(locale, { en: 'Choose a journey to explore or tell us the one you have in mind.', es: 'Elige un viaje para explorar o cuéntanos el que tienes en mente.', it: 'Scegli un viaggio da esplorare o raccontaci quello che hai in mente.', ar: 'اختر رحلة جاهزة أو احكِ لنا عن الرحلة التي تتخيلها.' })}</p><div className="about-hero-actions"><Link href="/trips" className="primary-btn">{tx(locale, { en: 'See all trips', es: 'Ver todos los viajes', it: 'Vedi tutti i viaggi', ar: 'شاهد كل الرحلات' })} <ArrowRight size={17}/></Link><Link href="/contact" className="about-hero-link">{tx(locale, { en: 'Contact us', es: 'Contáctanos', it: 'Contattaci', ar: 'تواصل معنا' })} <ArrowRight size={17}/></Link></div></div></section>
    <HelpCTA />
  </main>
}

export function AboutPage() {
  return <SiteShell><AboutContent /></SiteShell>
}
